"""Execute one refresh job (Feature 024).

A ``refresh_race`` job runs a FULL pass — entries + results + odds — in one go (the safety rules in
the scrape layer make this safe at any race state): entries auto-creates the Race/horses + completes
pedigree, results are INSERT-only (never clobber JRA-VAN finals), odds fill-null on finished races /
overwrite while pending. A future (not-yet-run) race simply has no result page yet, so the results
sub-step is best-effort and degrades the job to PARTIAL rather than failing it.

A ``refresh_day`` job DISCOVERS the day's races from netkeiba (``discover_races``) and fans out one
``refresh_race`` child per race (the worker then drains the children). Discovery/fanout runs in the
worker — never in the request handler — so the POST returns 202 without a netkeiba round-trip.

The underlying scrape_* helpers record their own ingestion_jobs rows + commit; here we roll their
counts onto the orchestration row. Ingested odds/results never become model features (II).
"""

from __future__ import annotations

import datetime
import os
import subprocess
from pathlib import Path

import httpx
from horseracing_db.enums import JobStatus
from horseracing_db.models import IngestionJob, RaceResult
from horseracing_scrape.fetch import HttpFetcher
from horseracing_scrape.pipeline import (
    discover_races,
    scrape_entries,
    scrape_odds,
    scrape_results,
)
from horseracing_scrape.urls import entries_url, result_url, win_odds_url
from sqlalchemy import func, select
from sqlalchemy.orm import Session

from .deps import owner_database_url
from .enqueue import enqueue_race

_USER_AGENT = "horseracing-ops/0.1 (personal use; contact via repo)"

#: Feature 028: the ops (write/ingest) path must NOT import the model/feature stack (boundary II/VI,
#: tests/integration/test_boundary.py). So predict shells out to the serving CLI in its OWN env via
#: uv, keeping ops's import graph clean. The subprocess persists prediction_runs itself.
_SERVING_DIR = Path(__file__).resolve().parents[3] / "serving"
_SERVING_TIMEOUT_S = 300

#: Feature 043: recommendations are generated by the betting stack, which transitively imports the
#: model stack (backtest → serving). So ops shells out to the betting CLI too (same boundary rule as
#: predict). The CLI resolves the active-model run, is idempotent, and persists recommendations.
_BETTING_DIR = Path(__file__).resolve().parents[3] / "betting"
_BETTING_TIMEOUT_S = 300


def make_fetcher(min_interval: float = 1.0, cache_dir: str | None = None) -> HttpFetcher:
    """A polite fetcher reusing scrape's robots/rate-limit/backoff/cache (FR-014).

    Crucially passes a real httpx client — without it the fetcher can only serve cached pages and
    every LIVE netkeiba fetch fails (robots check dereferences a None client)."""
    return HttpFetcher(
        user_agent=_USER_AGENT, min_interval_s=min_interval, cache_dir=cache_dir,
        client=httpx.Client(headers={"User-Agent": _USER_AGENT}, timeout=20.0),
    )


def _now() -> datetime.datetime:
    return datetime.datetime.now(datetime.UTC)


def is_result_pending(session: Session, race_id: str) -> bool:
    n = session.scalar(
        select(func.count()).select_from(RaceResult).where(RaceResult.race_id == race_id)
    )
    return not (n and n > 0)


def _terminal(*, entries_failed: bool, any_failed: bool, errors: int, written: int) -> str:
    if entries_failed:  # couldn't even build the entry population — a real failure
        return JobStatus.FAILED
    if any_failed or errors:  # e.g. a future race has no result page yet -> best-effort PARTIAL
        return JobStatus.PARTIAL
    if written == 0:
        # nothing ingested (page not published yet / no rows) — distinct from a real success
        return JobStatus.SKIPPED
    return JobStatus.SUCCEEDED


def run_one(session: Session, job: IngestionJob, *, fetcher=None) -> IngestionJob:
    """Full refresh of one race: entries + results + odds. Sets terminal status/counts, commits.

    All three run regardless of result-pending state — the scrape-layer safety rules keep it sound
    (results INSERT-only, odds fill-null-on-finished / overwrite-on-pending). A not-yet-run race has
    no result page, so its results sub-step fails benignly and the job ends PARTIAL, not FAILED."""
    fetcher = fetcher or make_fetcher()
    race_id = job.scope_value or ""

    entries = scrape_entries(session, urls=[entries_url(race_id)], fetcher=fetcher,
                             scope_value=race_id)
    results = scrape_results(session, urls=[result_url(race_id)], fetcher=fetcher,
                             scope_value=race_id)
    odds = scrape_odds(session, urls=[win_odds_url(race_id)], fetcher=fetcher, scope_value=race_id)
    summaries = [entries, results, odds]

    written = sum(s.written for s in summaries)
    errors = sum(s.errors for s in summaries)
    job.status = _terminal(
        entries_failed=(entries.status == JobStatus.FAILED),
        any_failed=any(s.status == JobStatus.FAILED for s in summaries),
        errors=errors, written=written,
    )
    job.processed_rows = sum(s.processed for s in summaries)
    job.skipped_rows = sum(s.skipped for s in summaries)
    job.error_count = errors
    job.completed_at = _now()
    job.summary = {
        "kind": "entries+results+odds",
        "written": written,
        "calls": [{"job_type": s.job_type, "status": s.status, "written": s.written,
                   "skipped": s.skipped, "errors": s.errors} for s in summaries],
    }
    session.add(job)
    session.commit()
    return job


def _serving_predict(race_id: str) -> subprocess.CompletedProcess:
    """Invoke the serving CLI in its OWN env (`uv run --project serving`) — ops must not import the
    model stack (boundary II/VI). The CLI builds as-of (leak-safe) features, runs the single active
    model, and persists the prediction_run; it prints a summary and exits 0 (incl. the empty
    "no races inferred" case) or non-zero on ServingError / failure. Monkeypatched in tests."""
    cmd = [
        "uv", "run", "--project", str(_SERVING_DIR), "python", "-m", "horseracing_serving",
        "predict", "--race-id", race_id, "--database-url", owner_database_url(),
    ]
    # cwd = serving/ so the model_versions.weights_uri (stored relative, e.g. ../artifacts/...)
    # resolves to <repo>/artifacts exactly as a normal serving run does. Drop VIRTUAL_ENV so uv
    # targets serving's env without a noisy mismatch warning (ops runs under its own venv).
    env = {k: v for k, v in os.environ.items() if k != "VIRTUAL_ENV"}
    return subprocess.run(  # noqa: S603 — fixed argv, race_id is endpoint-validated 12 digits
        cmd, capture_output=True, text=True, timeout=_SERVING_TIMEOUT_S,
        cwd=str(_SERVING_DIR), env=env,
    )


def run_predict(session: Session, job: IngestionJob, *, fetcher=None) -> IngestionJob:
    """Feature 028: generate predictions for one race by shelling out to the serving CLI (no scrape,
    so ``fetcher`` is unused — kept for the worker's uniform runner(session, job, fetcher=) call).

    Maps the CLI outcome to a terminal job status: non-zero exit (ServingError / failure) → FAILED
    (deterministic — not worker-retried); rc 0 + "no races inferred" → SKIPPED (no started horses,
    no half-baked run); otherwise → SUCCEEDED. The CLI persists prediction_runs itself; the audit
    (model_version/computed_at) lives there, so the job summary keeps just a short output tail."""
    race_id = job.scope_value or ""
    proc = _serving_predict(race_id)
    stdout = proc.stdout or ""
    tail = ((proc.stderr or "") + stdout).strip()[-500:]
    job.completed_at = _now()
    if proc.returncode != 0:
        job.status = JobStatus.FAILED
        job.error_message = tail
        job.summary = {"kind": "predict", "source": "manual", "error": tail}
    elif "no races inferred" in stdout:
        job.status = JobStatus.SKIPPED
        job.summary = {"kind": "predict", "source": "manual", "reason": "no started horses"}
    else:
        job.status = JobStatus.SUCCEEDED
        job.summary = {"kind": "predict", "source": "manual", "output": tail}
    session.add(job)
    session.commit()
    return job


def _betting_recommend(race_id: str) -> subprocess.CompletedProcess:
    """Invoke the betting CLI in its OWN env (`uv run --project betting`) — ops must not import the
    model/betting stack (boundary II/VI). ``recommend-serve`` resolves the active-model run,
    generates ONE coherent set (Kelly EV+stake), is idempotent, and prints OK:/SKIPPED:. Same env
    handling as _serving_predict (cwd=betting so relative artifact URIs resolve; drop VIRTUAL_ENV).
    Monkeypatched in tests."""
    cmd = [
        "uv", "run", "--project", str(_BETTING_DIR), "python", "-m", "horseracing_betting",
        "recommend-serve", "--race-id", race_id, "--database-url", owner_database_url(),
    ]
    env = {k: v for k, v in os.environ.items() if k != "VIRTUAL_ENV"}
    return subprocess.run(  # noqa: S603 — fixed argv, race_id is endpoint-validated 12 digits
        cmd, capture_output=True, text=True, timeout=_BETTING_TIMEOUT_S,
        cwd=str(_BETTING_DIR), env=env,
    )


def run_recommend(session: Session, job: IngestionJob, *, fetcher=None) -> IngestionJob:
    """Feature 043: generate buy recommendations for one race via the betting CLI (no scrape, so
    ``fetcher`` is unused — kept for the worker's uniform runner(session, job, fetcher=) call).

    Maps the CLI outcome to a terminal status (028-style): non-zero exit → FAILED (deterministic,
    not worker-retried); rc 0 + a "SKIPPED:" marker (no run / no odds / already generated) → SKIPPED
    (no half-baked state); otherwise → SUCCEEDED. The CLI persists recommendations itself."""
    race_id = job.scope_value or ""
    proc = _betting_recommend(race_id)
    stdout = proc.stdout or ""
    tail = ((proc.stderr or "") + stdout).strip()[-500:]
    job.completed_at = _now()
    if proc.returncode != 0:
        job.status = JobStatus.FAILED
        job.error_message = tail
        job.summary = {"kind": "recommend", "source": "manual", "error": tail}
    elif "SKIPPED:" in stdout:
        job.status = JobStatus.SKIPPED
        reason = stdout.split("SKIPPED:", 1)[1].strip()[:200]
        job.summary = {"kind": "recommend", "source": "manual", "reason": reason}
    else:
        job.status = JobStatus.SUCCEEDED
        job.summary = {"kind": "recommend", "source": "manual", "output": tail}
    session.add(job)
    session.commit()
    return job


def run_day(session: Session, job: IngestionJob, *, fetcher=None) -> IngestionJob:
    """Discover a day's races from netkeiba and fan out one refresh_race child per race.

    Runs in the worker (not the request handler). The children share the parent's trace_id so the
    batch poll (/batches/{trace_id}) aggregates them. 0 races (no JRA racing that day) is a clean
    no-op SUCCEEDED parent. The children are drained in subsequent worker iterations."""
    fetcher = fetcher or make_fetcher()
    date = datetime.date.fromisoformat(job.scope_value or "")
    listing = discover_races(fetcher, date.strftime("%Y%m%d"))

    n_new = 0
    for rid in listing.race_ids:
        _child, reused = enqueue_race(session, rid, trace_id=job.trace_id)
        if not reused:
            n_new += 1

    job.status = JobStatus.SUCCEEDED
    job.processed_rows = len(listing.race_ids)
    job.completed_at = _now()
    job.summary = {"kind": "discover", "races": len(listing.race_ids), "children_new": n_new}
    session.add(job)
    session.commit()
    return job


_LIVE_DIR = Path(__file__).resolve().parents[3] / "live"
_LIVE_TIMEOUT_S = 3600  # a ≤35-day range ≈ ≤12 race days × ~45s predict + recommend — ample


def _live_refresh(date_from: str, date_to: str) -> subprocess.CompletedProcess:
    """Feature 053: invoke the live CLI in its OWN env (`uv run --project live`) — ops must not
    import the live/serving/betting stack (boundary II/VI, same as _serving_predict). The 050
    `refresh` command is idempotent (predict backfill → recommend backfill, stage-isolated).
    Monkeypatched in tests."""
    cmd = [
        "uv", "run", "--project", str(_LIVE_DIR), "python", "-m", "horseracing_live",
        "refresh", "--from", date_from, "--to", date_to,
        "--database-url", owner_database_url(),
    ]
    env = {k: v for k, v in os.environ.items() if k != "VIRTUAL_ENV"}
    return subprocess.run(  # noqa: S603 — fixed argv, dates are endpoint-validated ISO dates
        cmd, capture_output=True, text=True, timeout=_LIVE_TIMEOUT_S,
        cwd=str(_LIVE_DIR), env=env,
    )


def run_refresh_range(session: Session, job: IngestionJob, *, fetcher=None) -> IngestionJob:
    """Feature 053: run a range refresh by shelling out to the live CLI (no scrape; ``fetcher``
    unused — kept for the worker's uniform runner call). rc 0 → SUCCEEDED (both stages ran; each
    is idempotent with per-race/day isolation, 050); non-zero → FAILED with the output tail."""
    scope_value = job.scope_value or ""
    date_from, _, date_to = scope_value.partition("..")
    proc = _live_refresh(date_from, date_to)
    stdout = proc.stdout or ""
    tail = ((proc.stderr or "") + stdout).strip()[-500:]
    job.completed_at = _now()
    if proc.returncode != 0:
        job.status = JobStatus.FAILED
        job.error_message = tail
        job.summary = {"kind": "refresh_range", "source": "manual", "error": tail}
    else:
        job.status = JobStatus.SUCCEEDED
        job.summary = {"kind": "refresh_range", "source": "manual", "output": tail}
    session.add(job)
    session.commit()
    return job
