"""Execute one refresh job (Feature 024).

A ``refresh_race`` job runs a FULL pass — entries + results + odds — in one go (the safety rules in
the scrape layer make this safe at any race state): entries auto-creates the Race/horses + completes
pedigree, results are INSERT-only (never clobber JRA-VAN finals), odds fill-null on finished races /
overwrite while pending. A future (not-yet-run) race simply has no result page yet, so the results
sub-step is best-effort and degrades the job to PARTIAL rather than failing it.

A ``refresh_day`` job DISCOVERS the day's races from netkeiba (``discover_races``) and fans out one
``refresh_race`` child per race (the worker then drains the children). Discovery/fanout runs in the
worker — never in the request handler — so the POST returns 202 without a netkeiba round-trip.

The underlying scrape_* helpers record their own ingestion_jobs rows + commit; here we roll their
counts onto the orchestration row. Ingested odds/results never become model features (II).
"""

from __future__ import annotations

import datetime
import os
import subprocess
from pathlib import Path

import httpx
from horseracing_db.enums import JobStatus
from horseracing_db.models import IngestionJob, ModelVersion, PredictionRun, RaceResult
from horseracing_scrape.fetch import HttpFetcher
from horseracing_scrape.pipeline import (
    discover_races,
    scrape_entries,
    scrape_odds,
    scrape_results,
)
from horseracing_scrape.urls import entries_url, result_url, win_odds_url
from sqlalchemy import func, select
from sqlalchemy.orm import Session

from .deps import owner_database_url
from .enqueue import enqueue_predict, enqueue_race, enqueue_recommend

_USER_AGENT = "horseracing-ops/0.1 (personal use; contact via repo)"

#: Feature 028: the ops (write/ingest) path must NOT import the model/feature stack (boundary II/VI,
#: tests/integration/test_boundary.py). So predict shells out to the serving CLI in its OWN env via
#: uv, keeping ops's import graph clean. The subprocess persists prediction_runs itself.
_SERVING_DIR = Path(__file__).resolve().parents[3] / "serving"
_SERVING_TIMEOUT_S = 300

#: Feature 043: recommendations are generated by the betting stack, which transitively imports the
#: model stack (backtest → serving). So ops shells out to the betting CLI too (same boundary rule as
#: predict). The CLI resolves the active-model run, is idempotent, and persists recommendations.
_BETTING_DIR = Path(__file__).resolve().parents[3] / "betting"
_BETTING_TIMEOUT_S = 300


def make_fetcher(min_interval: float = 1.0, cache_dir: str | None = None) -> HttpFetcher:
    """A polite fetcher reusing scrape's robots/rate-limit/backoff/cache (FR-014).

    Crucially passes a real httpx client — without it the fetcher can only serve cached pages and
    every LIVE netkeiba fetch fails (robots check dereferences a None client)."""
    return HttpFetcher(
        user_agent=_USER_AGENT, min_interval_s=min_interval, cache_dir=cache_dir,
        client=httpx.Client(headers={"User-Agent": _USER_AGENT}, timeout=20.0),
    )


def _now() -> datetime.datetime:
    return datetime.datetime.now(datetime.UTC)


def is_result_pending(session: Session, race_id: str) -> bool:
    n = session.scalar(
        select(func.count()).select_from(RaceResult).where(RaceResult.race_id == race_id)
    )
    return not (n and n > 0)


def _terminal(*, entries_failed: bool, any_failed: bool, errors: int, written: int) -> str:
    if entries_failed:  # couldn't even build the entry population — a real failure
        return JobStatus.FAILED
    if any_failed or errors:  # e.g. a future race has no result page yet -> best-effort PARTIAL
        return JobStatus.PARTIAL
    if written == 0:
        # nothing ingested (page not published yet / no rows) — distinct from a real success
        return JobStatus.SKIPPED
    return JobStatus.SUCCEEDED


def _has_active_prediction(session: Session, race_id: str) -> bool:
    """True if ``race_id`` already has a prediction_run for the currently ACTIVE model — the same
    run the read API (014 select_prediction_run) would surface. Used to precompute predictions
    ONCE per race (below) without re-predicting on every odds refresh. Pure DB read (no ML import —
    boundary II/VI): ops resolves the active model straight from model_versions."""
    active = session.scalars(
        select(ModelVersion.model_version).where(ModelVersion.adoption_status == "active")
    ).first()
    if active is None:  # no active model → nothing meaningful to precompute; leave it to a click
        return True
    return (
        session.scalars(
            select(PredictionRun.prediction_run_id)
            .where(PredictionRun.race_id == race_id)
            .where(PredictionRun.model_version == active)
        ).first()
        is not None
    )


def run_one(session: Session, job: IngestionJob, *, fetcher=None) -> IngestionJob:
    """Full refresh of one race: entries + results + odds. Sets terminal status/counts, commits.

    All three run regardless of result-pending state — the scrape-layer safety rules keep it sound
    (results INSERT-only, odds fill-null-on-finished / overwrite-on-pending). A not-yet-run race has
    no result page, so its results sub-step fails benignly and the job ends PARTIAL, not FAILED.

    Precompute (predict-ahead): once entries land, chase them with a predict job so the race-detail
    page reads a persisted run instead of blocking on a ~1-minute on-demand build. Only when entries
    didn't fail AND the ACTIVE model has no run yet (so repeated odds refreshes don't re-predict);
    predict itself is odds-independent for the default model (a market-offset model just typed-skips
    until odds exist). Follow-up job (not in-job chaining) so enqueue_predict's in-flight dedup
    converges with a concurrent manual 予測生成. The predict job then chains recommend as usual."""
    fetcher = fetcher or make_fetcher()
    race_id = job.scope_value or ""

    entries = scrape_entries(session, urls=[entries_url(race_id)], fetcher=fetcher,
                             scope_value=race_id)
    results = scrape_results(session, urls=[result_url(race_id)], fetcher=fetcher,
                             scope_value=race_id)
    odds = scrape_odds(session, urls=[win_odds_url(race_id)], fetcher=fetcher, scope_value=race_id)
    summaries = [entries, results, odds]

    written = sum(s.written for s in summaries)
    errors = sum(s.errors for s in summaries)
    job.status = _terminal(
        entries_failed=(entries.status == JobStatus.FAILED),
        any_failed=any(s.status == JobStatus.FAILED for s in summaries),
        errors=errors, written=written,
    )
    job.processed_rows = sum(s.processed for s in summaries)
    job.skipped_rows = sum(s.skipped for s in summaries)
    job.error_count = errors
    job.completed_at = _now()
    summary = {
        "kind": "entries+results+odds",
        "written": written,
        "calls": [{"job_type": s.job_type, "status": s.status, "written": s.written,
                   "skipped": s.skipped, "errors": s.errors} for s in summaries],
    }
    # precompute predictions once entries exist (see docstring). enqueue in THIS transaction, then
    # assign summary ONCE (a later in-place mutation of a flushed dict is invisible to JSONB change
    # tracking — same pattern as run_predict's recommend follow-up).
    if entries.status != JobStatus.FAILED and not _has_active_prediction(session, race_id):
        followup, reused = enqueue_predict(session, race_id)
        if not reused:
            summary["predict_job_id"] = str(followup.ingestion_job_id)
    job.summary = summary
    session.add(job)
    session.commit()
    return job


def _calib_argv(prefix: str) -> list[str]:
    """Feature 076 (076-gap): opt-in manifest activation for a per-race ops subprocess via env.

    ``<prefix>_CALIB_MANIFEST`` (absolute) + ``<prefix>_CALIB_MODE=manifest-required`` forward the
    calib flags to the CLI argv (same as _live_refresh + the api DISPERSION_CALIB_MANIFEST pattern).
    Default-off, so the REST payload/contract is unchanged and ops stays ML-free — it only forwards
    argv; the manifest is verified inside the subprocess (fail-closed → rc!=0 → job FAILED). This is
    the do-not-default-ON waiver until real manifest generation (078)."""
    manifest = os.environ.get(f"{prefix}_CALIB_MANIFEST") or None
    mode = os.environ.get(f"{prefix}_CALIB_MODE", "legacy-runtime")
    if mode == "manifest-required" and manifest:
        return ["--calib-manifest", manifest, "--calib-mode", "manifest-required"]
    return []


def _serving_predict(race_id: str) -> subprocess.CompletedProcess:
    """Invoke the serving CLI in its OWN env (`uv run --project serving`) — ops must not import the
    model stack (boundary II/VI). The CLI builds as-of (leak-safe) features, runs the single active
    model, and persists the prediction_run; it prints a summary and exits 0 (incl. the empty
    "no races inferred" case) or non-zero on ServingError / failure. Monkeypatched in tests."""
    cmd = [
        "uv", "run", "--project", str(_SERVING_DIR), "python", "-m", "horseracing_serving",
        "predict", "--race-id", race_id, "--database-url", owner_database_url(),
        *_calib_argv("PREDICT"),  # Feature 076: opt-in manifest activation via env
    ]
    # cwd = serving/ so the model_versions.weights_uri (stored relative, e.g. ../artifacts/...)
    # resolves to <repo>/artifacts exactly as a normal serving run does. Drop VIRTUAL_ENV so uv
    # targets serving's env without a noisy mismatch warning (ops runs under its own venv).
    env = {k: v for k, v in os.environ.items() if k != "VIRTUAL_ENV"}
    return subprocess.run(  # noqa: S603 — fixed argv, race_id is endpoint-validated 12 digits
        cmd, capture_output=True, text=True, timeout=_SERVING_TIMEOUT_S,
        cwd=str(_SERVING_DIR), env=env,
    )


def run_predict(session: Session, job: IngestionJob, *, fetcher=None) -> IngestionJob:
    """Feature 028: generate predictions for one race by shelling out to the serving CLI (no scrape,
    so ``fetcher`` is unused — kept for the worker's uniform runner(session, job, fetcher=) call).

    Maps the CLI outcome to a terminal job status: non-zero exit (ServingError / failure) → FAILED
    (deterministic — not worker-retried); rc 0 + "no races inferred" → SKIPPED (no started horses,
    no half-baked run); otherwise → SUCCEEDED. The CLI persists prediction_runs itself; the audit
    (model_version/computed_at) lives there, so the job summary keeps just a short output tail."""
    race_id = job.scope_value or ""
    proc = _serving_predict(race_id)
    stdout = proc.stdout or ""
    tail = ((proc.stderr or "") + stdout).strip()[-500:]
    job.completed_at = _now()
    if proc.returncode != 0:
        job.status = JobStatus.FAILED
        job.error_message = tail
        job.summary = {"kind": "predict", "source": "manual", "error": tail}
    elif "no races inferred" in stdout:
        job.status = JobStatus.SKIPPED
        job.summary = {"kind": "predict", "source": "manual", "reason": "no started horses"}
    else:
        job.status = JobStatus.SUCCEEDED
        # 043 deferred item: a fresh prediction_run starts with zero recommendations (they are
        # per-run), so chase the new run with a recommend job — the user gets buy-ups without a
        # second click. Follow-up-job (not in-job chaining) so enqueue_recommend's in-flight dedup
        # converges with a concurrent manual 買い目生成 instead of double-generating. Same
        # transaction as the terminal predict status (committed below). summary is assigned ONCE
        # after the enqueue — its session.flush() would otherwise write the dict early and a later
        # in-place mutation is invisible to JSONB change tracking (no MutableDict).
        followup, _ = enqueue_recommend(session, race_id, source="auto_after_predict",
                                        reuse_running=False)
        job.summary = {"kind": "predict", "source": "manual", "output": tail,
                       "recommend_job_id": str(followup.ingestion_job_id)}
    session.add(job)
    session.commit()
    return job


def _betting_recommend(race_id: str) -> subprocess.CompletedProcess:
    """Invoke the betting CLI in its OWN env (`uv run --project betting`) — ops must not import the
    model/betting stack (boundary II/VI). ``recommend-serve`` resolves the active-model run,
    generates ONE coherent set (Kelly EV+stake), is idempotent, and prints OK:/SKIPPED:. Same env
    handling as _serving_predict (cwd=betting so relative artifact URIs resolve; drop VIRTUAL_ENV).
    Monkeypatched in tests."""
    cmd = [
        "uv", "run", "--project", str(_BETTING_DIR), "python", "-m", "horseracing_betting",
        "recommend-serve", "--race-id", race_id, "--database-url", owner_database_url(),
        *_calib_argv("RECOMMEND"),  # Feature 076: opt-in manifest activation via env
    ]
    env = {k: v for k, v in os.environ.items() if k != "VIRTUAL_ENV"}
    return subprocess.run(  # noqa: S603 — fixed argv, race_id is endpoint-validated 12 digits
        cmd, capture_output=True, text=True, timeout=_BETTING_TIMEOUT_S,
        cwd=str(_BETTING_DIR), env=env,
    )


def run_recommend(session: Session, job: IngestionJob, *, fetcher=None) -> IngestionJob:
    """Feature 043: generate buy recommendations for one race via the betting CLI (no scrape, so
    ``fetcher`` is unused — kept for the worker's uniform runner(session, job, fetcher=) call).

    Maps the CLI outcome to a terminal status (028-style): non-zero exit → FAILED (deterministic,
    not worker-retried); rc 0 + a "SKIPPED:" marker (no run / no odds / already generated) → SKIPPED
    (no half-baked state); otherwise → SUCCEEDED. The CLI persists recommendations itself."""
    race_id = job.scope_value or ""
    # preserve the enqueue-time audit label ("manual" button / "auto_after_predict" follow-up)
    source = (job.summary or {}).get("source", "manual")
    proc = _betting_recommend(race_id)
    stdout = proc.stdout or ""
    tail = ((proc.stderr or "") + stdout).strip()[-500:]
    job.completed_at = _now()
    if proc.returncode != 0:
        job.status = JobStatus.FAILED
        job.error_message = tail
        job.summary = {"kind": "recommend", "source": source, "error": tail}
    elif "SKIPPED:" in stdout:
        job.status = JobStatus.SKIPPED
        reason = stdout.split("SKIPPED:", 1)[1].strip()[:200]
        job.summary = {"kind": "recommend", "source": source, "reason": reason}
    else:
        job.status = JobStatus.SUCCEEDED
        job.summary = {"kind": "recommend", "source": source, "output": tail}
    session.add(job)
    session.commit()
    return job


def run_day(session: Session, job: IngestionJob, *, fetcher=None) -> IngestionJob:
    """Discover a day's races from netkeiba and fan out one refresh_race child per race.

    Runs in the worker (not the request handler). The children share the parent's trace_id so the
    batch poll (/batches/{trace_id}) aggregates them. 0 races (no JRA racing that day) is a clean
    no-op SUCCEEDED parent. The children are drained in subsequent worker iterations."""
    fetcher = fetcher or make_fetcher()
    date = datetime.date.fromisoformat(job.scope_value or "")
    listing = discover_races(fetcher, date.strftime("%Y%m%d"))

    n_new = 0
    for rid in listing.race_ids:
        _child, reused = enqueue_race(session, rid, trace_id=job.trace_id)
        if not reused:
            n_new += 1

    job.status = JobStatus.SUCCEEDED
    job.processed_rows = len(listing.race_ids)
    job.completed_at = _now()
    job.summary = {"kind": "discover", "races": len(listing.race_ids), "children_new": n_new}
    session.add(job)
    session.commit()
    return job


_LIVE_DIR = Path(__file__).resolve().parents[3] / "live"
_LIVE_TIMEOUT_S = 3600  # a ≤35-day range ≈ ≤12 race days × ~45s predict + recommend — ample


def _live_refresh(
    date_from: str, date_to: str,
    *, calib_manifest: str | None = None, calib_mode: str = "legacy-runtime",
) -> subprocess.CompletedProcess:
    """Feature 053: invoke the live CLI in its OWN env (`uv run --project live`) — ops must not
    import the live/serving/betting stack (boundary II/VI, same as _serving_predict). The 050
    `refresh` command is idempotent (predict backfill → recommend backfill, stage-isolated).
    Monkeypatched in tests.

    Feature 076 (T018): when a manifest is configured (env, see ``run_refresh_range``), forward the
    calib flags to the SAME live CLI loader so the ops subprocess resolves the SAME manifest_digest
    as a direct CLI run (SC-011). The manifest itself is verified inside the subprocess (fail-closed
    → rc!=0 → job FAILED); ops stays ML-free (it only forwards argv)."""
    cmd = [
        "uv", "run", "--project", str(_LIVE_DIR), "python", "-m", "horseracing_live",
        "refresh", "--from", date_from, "--to", date_to,
        "--database-url", owner_database_url(),
    ]
    if calib_mode == "manifest-required" and calib_manifest:
        cmd += ["--calib-manifest", calib_manifest, "--calib-mode", "manifest-required"]
    env = {k: v for k, v in os.environ.items() if k != "VIRTUAL_ENV"}
    return subprocess.run(  # noqa: S603 — fixed argv, dates are endpoint-validated ISO dates
        cmd, capture_output=True, text=True, timeout=_LIVE_TIMEOUT_S,
        cwd=str(_LIVE_DIR), env=env,
    )


def run_refresh_range(session: Session, job: IngestionJob, *, fetcher=None) -> IngestionJob:
    """Feature 053: run a range refresh by shelling out to the live CLI (no scrape; ``fetcher``
    unused — kept for the worker's uniform runner call). rc 0 → SUCCEEDED (both stages ran; each
    is idempotent with per-race/day isolation, 050); non-zero → FAILED with the output tail."""
    scope_value = job.scope_value or ""
    date_from, _, date_to = scope_value.partition("..")
    # Feature 076 (T018): manifest activation is operator-supplied via env (opt-in, NOT a default —
    # the do-not-default-ON waiver), mirroring the api dispersion DISPERSION_CALIB_MANIFEST pattern.
    # The REST payload/contract is unchanged; ops just forwards the flags to the live subprocess.
    calib_manifest = os.environ.get("REFRESH_CALIB_MANIFEST") or None
    calib_mode = os.environ.get("REFRESH_CALIB_MODE", "legacy-runtime")
    if calib_mode == "manifest-required" and calib_manifest:
        proc = _live_refresh(date_from, date_to,
                             calib_manifest=calib_manifest, calib_mode=calib_mode)
    else:  # default: unchanged 2-arg call (backward-compatible)
        proc = _live_refresh(date_from, date_to)
    stdout = proc.stdout or ""
    tail = ((proc.stderr or "") + stdout).strip()[-500:]
    job.completed_at = _now()
    if proc.returncode != 0:
        job.status = JobStatus.FAILED
        job.error_message = tail
        job.summary = {"kind": "refresh_range", "source": "manual", "error": tail}
    else:
        job.status = JobStatus.SUCCEEDED
        job.summary = {"kind": "refresh_range", "source": "manual", "output": tail}
    session.add(job)
    session.commit()
    return job
