"""Export and pin the frozen Feature 084 SC-008 outcome fixture."""

from __future__ import annotations

import argparse
import datetime
import hashlib
import json
import os
from pathlib import Path

from horseracing_training.cli import main as training_main

_REPO_ROOT = Path(__file__).resolve().parents[2]
_ARTIFACT_DIGEST = "20d1e000de200a2a1ad0687ba9456cf12121f1b575dc5d87a7d482e9f9f83680"
_DEFAULT_ARTIFACT = (
    _REPO_ROOT / "artifacts" / "chaos_bands" / f"{_ARTIFACT_DIGEST}.json"
)
_FIXTURE_DIR = _REPO_ROOT / "training" / "tests" / "fixtures"
_DEFAULT_OUTPUT = _FIXTURE_DIR / "chaos_outcome_2024_plus.parquet"
_METADATA_PATH = _FIXTURE_DIR / "chaos_outcome_fixture.json"


def _date(value: str) -> datetime.date:
    try:
        return datetime.date.fromisoformat(value)
    except ValueError as exc:
        raise argparse.ArgumentTypeError(f"invalid ISO date: {value}") from exc


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--from", dest="date_from", type=_date, default=datetime.date(2024, 1, 1))
    parser.add_argument("--to", dest="date_to", type=_date, default=datetime.date(2026, 12, 31))
    parser.add_argument("--artifact", type=Path, default=_DEFAULT_ARTIFACT)
    parser.add_argument("--output", type=Path, default=_DEFAULT_OUTPUT)
    parser.add_argument(
        "--bootstrap-b",
        type=int,
        default=1,
        help="diagnostic bootstrap replicates; fixture contents do not depend on this (default: 1)",
    )
    parser.add_argument("--database-url", default=None)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    cli_args = [
        "chaos-bands",
        "diagnose",
        "--from",
        args.date_from.isoformat(),
        "--to",
        args.date_to.isoformat(),
        "--artifact",
        str(args.artifact),
        "--bootstrap-b",
        str(args.bootstrap_b),
        "--export-fixture",
        str(args.output),
    ]
    if args.database_url is not None:
        cli_args.extend(("--database-url", args.database_url))

    result = training_main(cli_args)
    if result != 0:
        return result

    digest = hashlib.sha256(args.output.read_bytes()).hexdigest()
    artifact_payload = json.loads(args.artifact.read_text(encoding="utf-8"))
    artifact_digest = str(artifact_payload["artifact_digest"])
    metadata = {
        "_comment": (
            "# ORCHESTRATOR: generated by training/scripts/"
            "export_chaos_outcome_fixture.py"
        ),
        "parquet": Path(os.path.relpath(args.output, _METADATA_PATH.parent)).as_posix(),
        "sha256": digest,
        "artifact_digest": artifact_digest,
    }
    _METADATA_PATH.write_text(
        json.dumps(metadata, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"pinned fixture metadata: {_METADATA_PATH} sha256={digest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
