/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Read-only readiness: DB connectivity + alembic schema-at-head (Feature 018, fail-closed).
         *
         *     503 when the DB is unreachable OR applied migration != bundled head, so the deploy healthcheck
         *     blocks serving on an un-migrated DB. SELECT-only — no write path added (014 stays read-only).
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/horses/{horse_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Horse */
        get: operations["get_horse_api_v1_horses__horse_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/horses/{horse_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Horse History */
        get: operations["get_horse_history_api_v1_horses__horse_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jockeys/{jockey_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Jockey */
        get: operations["get_jockey_api_v1_jockeys__jockey_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jockeys/{jockey_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Jockey History */
        get: operations["get_jockey_history_api_v1_jockeys__jockey_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{model_version}/calibration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calibration */
        get: operations["calibration_api_v1_models__model_version__calibration_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/races": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Races */
        get: operations["races_api_v1_races_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/races/{race_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Race Detail */
        get: operations["race_detail_api_v1_races__race_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/races/{race_id}/odds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Odds */
        get: operations["odds_api_v1_races__race_id__odds_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/races/{race_id}/predictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Predictions */
        get: operations["predictions_api_v1_races__race_id__predictions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/races/{race_id}/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recommendations */
        get: operations["recommendations_api_v1_races__race_id__recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CalibrationBin */
        CalibrationBin: {
            /** Count */
            count: number;
            /** Pred Hi */
            pred_hi: number;
            /** Pred Lo */
            pred_lo: number;
            /** Pred Mean */
            pred_mean?: number | null;
            /** Realized Ci High */
            realized_ci_high?: number | null;
            /** Realized Ci Low */
            realized_ci_low?: number | null;
            /** Realized Rate */
            realized_rate?: number | null;
            /**
             * Suppressed
             * @default false
             */
            suppressed: boolean;
        };
        /** CalibrationResponse */
        CalibrationResponse: {
            /**
             * Bins
             * @default []
             */
            bins: components["schemas"]["CalibrationBin"][];
            /** Ece */
            ece?: number | null;
            /**
             * Label
             * @default win
             */
            label: string;
            /** Model Version */
            model_version: string;
            /**
             * N Total
             * @default 0
             */
            n_total: number;
            /**
             * Oos
             * @default true
             */
            oos: boolean;
            /**
             * Source
             * @default walk_forward_oos
             * @constant
             */
            source: "walk_forward_oos";
            /**
             * Valid Years
             * @default []
             */
            valid_years: number[];
        };
        /** EstimatedOddsRow */
        EstimatedOddsRow: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Bet Type */
            bet_type: string;
            /**
             * Is Estimated
             * @default true
             * @constant
             */
            is_estimated: true;
            /** Odds */
            odds?: number | null;
            /**
             * Odds Source
             * @default estimated
             * @constant
             */
            odds_source: "estimated";
            /**
             * Pseudo
             * @default true
             * @constant
             */
            pseudo: true;
            /** Selection */
            selection: number[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HorseEntry */
        HorseEntry: {
            /** Age */
            age?: number | null;
            /** Entry Status */
            entry_status: string;
            /** Frame */
            frame?: number | null;
            /** Horse Id */
            horse_id: string;
            /** Horse Name */
            horse_name?: string | null;
            /** Horse Number */
            horse_number?: number | null;
            /** Jockey Id */
            jockey_id?: string | null;
            /** Jockey Name */
            jockey_name?: string | null;
            /** Jockey Weight */
            jockey_weight?: number | null;
            /** Odds */
            odds?: number | null;
            /** Popularity */
            popularity?: number | null;
            /** Sex */
            sex?: string | null;
            /** Trainer Id */
            trainer_id?: string | null;
            /** Trainer Name */
            trainer_name?: string | null;
            /** Weight */
            weight?: number | null;
            /** Weight Diff */
            weight_diff?: number | null;
        };
        /** HorseHistoryRow */
        HorseHistoryRow: {
            /** Distance */
            distance?: number | null;
            /** Entry Status */
            entry_status?: string | null;
            /** Finish Order */
            finish_order?: number | null;
            /** Finish Time Sec */
            finish_time_sec?: number | null;
            /** Horse Number */
            horse_number?: number | null;
            /** Last 3F */
            last_3f?: number | null;
            /** Odds */
            odds?: number | null;
            /** Popularity */
            popularity?: number | null;
            /** Race Class */
            race_class?: string | null;
            /** Race Date */
            race_date?: string | null;
            /** Race Id */
            race_id: string;
            /** Race Name */
            race_name?: string | null;
            /** Race Number */
            race_number?: number | null;
            /** Result Status */
            result_status?: string | null;
            /** Track Type */
            track_type?: string | null;
            /** Venue Code */
            venue_code?: string | null;
        };
        /** HorsePrediction */
        HorsePrediction: {
            /** Horse Id */
            horse_id: string;
            /** Horse Number */
            horse_number?: number | null;
            /** Market Win Prob */
            market_win_prob?: number | null;
            /** Prior Starts Band */
            prior_starts_band?: ("few" | "some" | "many") | null;
            /** Top2 */
            top2?: number | null;
            /** Top3 */
            top3?: number | null;
            /** Win */
            win?: number | null;
        };
        /** HorseProfile */
        HorseProfile: {
            /** Avg Finish */
            avg_finish?: number | null;
            /** Birth Year */
            birth_year?: number | null;
            /** Dam Name */
            dam_name?: string | null;
            /** Damsire Name */
            damsire_name?: string | null;
            /** Data Source */
            data_source?: string | null;
            /** Horse Id */
            horse_id: string;
            /** Horse Name */
            horse_name?: string | null;
            /** Quinella Rate */
            quinella_rate?: number | null;
            /**
             * Seconds In
             * @default 0
             */
            seconds_in: number;
            /** Sex */
            sex?: string | null;
            /** Show Rate */
            show_rate?: number | null;
            /**
             * Shows In
             * @default 0
             */
            shows_in: number;
            /** Sire Name */
            sire_name?: string | null;
            /**
             * Starts
             * @default 0
             */
            starts: number;
            /** Win Rate */
            win_rate?: number | null;
            /**
             * Wins
             * @default 0
             */
            wins: number;
        };
        /** JockeyHistoryRow */
        JockeyHistoryRow: {
            /** Finish Order */
            finish_order?: number | null;
            /** Horse Id */
            horse_id?: string | null;
            /** Horse Name */
            horse_name?: string | null;
            /** Race Date */
            race_date?: string | null;
            /** Race Id */
            race_id: string;
            /** Race Name */
            race_name?: string | null;
            /** Race Number */
            race_number?: number | null;
            /** Result Status */
            result_status?: string | null;
            /** Venue Code */
            venue_code?: string | null;
        };
        /** JockeyProfile */
        JockeyProfile: {
            /** Avg Finish */
            avg_finish?: number | null;
            /** Jockey Id */
            jockey_id: string;
            /** Jockey Name */
            jockey_name?: string | null;
            /**
             * Mounts
             * @default 0
             */
            mounts: number;
            /** Quinella Rate */
            quinella_rate?: number | null;
            /**
             * Seconds In
             * @default 0
             */
            seconds_in: number;
            /** Show Rate */
            show_rate?: number | null;
            /**
             * Shows In
             * @default 0
             */
            shows_in: number;
            /** Win Rate */
            win_rate?: number | null;
            /**
             * Wins
             * @default 0
             */
            wins: number;
        };
        /** JointEntry */
        JointEntry: {
            /** Prob */
            prob: number;
            /** Selection */
            selection: number[];
        };
        /** OddsResponse */
        OddsResponse: {
            /**
             * Estimated
             * @default []
             */
            estimated: components["schemas"]["EstimatedOddsRow"][];
            /** Race Id */
            race_id: string;
            /**
             * Real Exotic
             * @default []
             */
            real_exotic: components["schemas"]["RealExoticOddsRow"][];
            /**
             * Win
             * @default []
             */
            win: components["schemas"]["WinOddsRow"][];
        };
        /** Page[HorseHistoryRow] */
        Page_HorseHistoryRow_: {
            /** Has Next */
            has_next: boolean;
            /** Items */
            items: components["schemas"]["HorseHistoryRow"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** Page[JockeyHistoryRow] */
        Page_JockeyHistoryRow_: {
            /** Has Next */
            has_next: boolean;
            /** Items */
            items: components["schemas"]["JockeyHistoryRow"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** Page[RaceSummary] */
        Page_RaceSummary_: {
            /** Has Next */
            has_next: boolean;
            /** Items */
            items: components["schemas"]["RaceSummary"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** PredictionResponse */
        PredictionResponse: {
            /** Canonical Consistent */
            canonical_consistent?: boolean | null;
            /**
             * Horses
             * @default []
             */
            horses: components["schemas"]["HorsePrediction"][];
            /** Joint */
            joint?: components["schemas"]["JointEntry"][] | null;
            /** Joint Bet Type */
            joint_bet_type?: string | null;
            /** Joint Logic Version */
            joint_logic_version?: string | null;
            /** Market Prob Source */
            market_prob_source?: "win_odds_vote_share" | null;
            /** Odds As Of */
            odds_as_of?: string | null;
            /** Odds Source */
            odds_source?: ("final" | "prerace") | null;
            /** Race Id */
            race_id: string;
            run?: components["schemas"]["RunAudit"] | null;
        };
        /** RaceDetail */
        RaceDetail: {
            /** Distance */
            distance?: number | null;
            /**
             * Has Results
             * @default false
             */
            has_results: boolean;
            /** Horses */
            horses: components["schemas"]["HorseEntry"][];
            /** Post Time */
            post_time?: string | null;
            /** Race Class */
            race_class?: string | null;
            /** Race Date */
            race_date?: string | null;
            /** Race Id */
            race_id: string;
            /** Race Name */
            race_name?: string | null;
            /** Race Number */
            race_number?: number | null;
            /** Track Type */
            track_type?: string | null;
            /** Venue Code */
            venue_code?: string | null;
        };
        /** RaceSummary */
        RaceSummary: {
            /** Distance */
            distance?: number | null;
            /**
             * Has Results
             * @default false
             */
            has_results: boolean;
            /** Post Time */
            post_time?: string | null;
            /** Race Class */
            race_class?: string | null;
            /** Race Date */
            race_date?: string | null;
            /** Race Id */
            race_id: string;
            /** Race Name */
            race_name?: string | null;
            /** Race Number */
            race_number?: number | null;
            /** Track Type */
            track_type?: string | null;
            /** Venue Code */
            venue_code?: string | null;
        };
        /** RealExoticOddsRow */
        RealExoticOddsRow: {
            /** Bet Type */
            bet_type: string;
            /** Coverage Scope */
            coverage_scope?: string | null;
            /**
             * Is Estimated
             * @default false
             * @constant
             */
            is_estimated: false;
            /** Odds */
            odds?: number | null;
            /**
             * Odds Source
             * @default real
             * @constant
             */
            odds_source: "real";
            /** Selection */
            selection: number[];
            /** Updated At */
            updated_at?: string | null;
        };
        /** RecommendationResponse */
        RecommendationResponse: {
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["RecommendationRow"][];
            /** Race Id */
            race_id: string;
        };
        /** RecommendationRow */
        RecommendationRow: {
            /** Bet Type */
            bet_type: string;
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            /** Double Pseudo */
            double_pseudo: boolean;
            /** Estimated Market Odds Used */
            estimated_market_odds_used?: number | null;
            /** Is Estimated Odds */
            is_estimated_odds: boolean;
            /** Logic Version */
            logic_version: string;
            /** Market Odds Used */
            market_odds_used?: number | null;
            /** Prediction Run Id */
            prediction_run_id: string;
            /** Pseudo Odds */
            pseudo_odds?: number | null;
            /** Pseudo Roi */
            pseudo_roi?: number | null;
            /** Selection */
            selection: number[];
        };
        /** RunAudit */
        RunAudit: {
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            /** Logic Version */
            logic_version: string;
            /** Model Version */
            model_version: string;
            /** Prediction Run Id */
            prediction_run_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WinOddsRow */
        WinOddsRow: {
            /** Horse Id */
            horse_id: string;
            /** Horse Number */
            horse_number?: number | null;
            /**
             * Is Estimated
             * @default false
             * @constant
             */
            is_estimated: false;
            /** Odds */
            odds?: number | null;
            /**
             * Odds Source
             * @default real
             * @constant
             */
            odds_source: "real";
            /** Updated At */
            updated_at?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_horse_api_v1_horses__horse_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                horse_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HorseProfile"];
                };
            };
            /** @description horse not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_horse_history_api_v1_horses__horse_id__history_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                horse_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_HorseHistoryRow_"];
                };
            };
            /** @description horse not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_jockey_api_v1_jockeys__jockey_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jockey_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JockeyProfile"];
                };
            };
            /** @description jockey not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_jockey_history_api_v1_jockeys__jockey_id__history_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                jockey_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_JockeyHistoryRow_"];
                };
            };
            /** @description jockey not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calibration_api_v1_models__model_version__calibration_get: {
        parameters: {
            query?: {
                label?: string;
            };
            header?: never;
            path: {
                model_version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    races_api_v1_races_get: {
        parameters: {
            query?: {
                date?: string | null;
                venue?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RaceSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    race_detail_api_v1_races__race_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                race_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RaceDetail"];
                };
            };
            /** @description race not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description bad race_id */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    odds_api_v1_races__race_id__odds_get: {
        parameters: {
            query?: {
                bet_type?: string | null;
                top?: number;
            };
            header?: never;
            path: {
                race_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OddsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predictions_api_v1_races__race_id__predictions_get: {
        parameters: {
            query?: {
                bet_type?: string | null;
                top?: number;
            };
            header?: never;
            path: {
                race_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommendations_api_v1_races__race_id__recommendations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                race_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
