/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coverage */
        get: operations["coverage_api_v1_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnostics/segment-edge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Segment Edge */
        get: operations["segment_edge_api_v1_diagnostics_segment_edge_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Read-only readiness: DB connectivity + alembic schema-at-head (Feature 018, fail-closed).
         *
         *     503 when the DB is unreachable OR applied migration != bundled head, so the deploy healthcheck
         *     blocks serving on an un-migrated DB. SELECT-only — no write path added (014 stays read-only).
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/horses/{horse_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Horse */
        get: operations["get_horse_api_v1_horses__horse_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/horses/{horse_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Horse History */
        get: operations["get_horse_history_api_v1_horses__horse_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jobs */
        get: operations["jobs_api_v1_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jockeys/{jockey_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Jockey */
        get: operations["get_jockey_api_v1_jockeys__jockey_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jockeys/{jockey_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Jockey History */
        get: operations["get_jockey_history_api_v1_jockeys__jockey_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Models */
        get: operations["models_api_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{model_version}/calibration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calibration */
        get: operations["calibration_api_v1_models__model_version__calibration_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{model_version}/importance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Importance */
        get: operations["importance_api_v1_models__model_version__importance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/races": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Races */
        get: operations["races_api_v1_races_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/races/{race_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Race Detail */
        get: operations["race_detail_api_v1_races__race_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/races/{race_id}/odds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Odds */
        get: operations["odds_api_v1_races__race_id__odds_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/races/{race_id}/predictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Predictions */
        get: operations["predictions_api_v1_races__race_id__predictions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/races/{race_id}/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recommendations */
        get: operations["recommendations_api_v1_races__race_id__recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AvailableModel
         * @description Feature 057: a model that has a persisted prediction_run for THIS race (i.e. selectable on
         *     the race-detail view). display_name/purpose are human labels (null until set). is_selected marks
         *     the model whose run this response returns. adoption_status lets the front badge the active model
         *     ('active') distinctly from the selected one (selected ≠ adopted).
         */
        AvailableModel: {
            /** Adoption Status */
            adoption_status: string;
            /** Display Name */
            display_name?: string | null;
            /** Is Selected */
            is_selected: boolean;
            /** Model Version */
            model_version: string;
            /** Purpose */
            purpose?: string | null;
        };
        /** CalibrationBin */
        CalibrationBin: {
            /** Count */
            count: number;
            /** Pred Hi */
            pred_hi: number;
            /** Pred Lo */
            pred_lo: number;
            /** Pred Mean */
            pred_mean?: number | null;
            /** Realized Ci High */
            realized_ci_high?: number | null;
            /** Realized Ci Low */
            realized_ci_low?: number | null;
            /** Realized Rate */
            realized_rate?: number | null;
            /**
             * Suppressed
             * @default false
             */
            suppressed: boolean;
        };
        /** CalibrationResponse */
        CalibrationResponse: {
            /**
             * Bins
             * @default []
             */
            bins: components["schemas"]["CalibrationBin"][];
            /** Ece */
            ece?: number | null;
            /**
             * Label
             * @default win
             */
            label: string;
            /** Model Version */
            model_version: string;
            /**
             * N Total
             * @default 0
             */
            n_total: number;
            /**
             * Oos
             * @default true
             */
            oos: boolean;
            /**
             * Source
             * @default walk_forward_oos
             * @constant
             */
            source: "walk_forward_oos";
            /**
             * Valid Years
             * @default []
             */
            valid_years: number[];
        };
        /**
         * CoverageDay
         * @description One race day's product coverage. n_predicted_active uses the ACTIVE model only (044
         *     idempotency semantics); 0 when no model is active.
         */
        CoverageDay: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** N Predicted Active */
            n_predicted_active: number;
            /** N Races */
            n_races: number;
            /** N With Odds */
            n_with_odds: number;
            /** N With Recommendations */
            n_with_recommendations: number;
            /** N With Results */
            n_with_results: number;
        };
        /** CoverageResponse */
        CoverageResponse: {
            /** Active Model Version */
            active_model_version?: string | null;
            /**
             * Date From
             * Format: date
             */
            date_from: string;
            /**
             * Date To
             * Format: date
             */
            date_to: string;
            /**
             * Days
             * @default []
             */
            days: components["schemas"]["CoverageDay"][];
        };
        /** EstimatedOddsRow */
        EstimatedOddsRow: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Bet Type */
            bet_type: string;
            /**
             * Is Estimated
             * @default true
             * @constant
             */
            is_estimated: true;
            /** Odds */
            odds?: number | null;
            /**
             * Odds Source
             * @default estimated
             * @constant
             */
            odds_source: "estimated";
            /**
             * Pseudo
             * @default true
             * @constant
             */
            pseudo: true;
            /** Selection */
            selection: number[];
        };
        /**
         * Explanation
         * @description Feature 040: display-only score-contribution explanation (persisted, read as-is).
         *
         *     Contributions decompose the RAW booster margin (before race-softmax / isotonic / 009), NOT the
         *     final probability. The front frames this as "score contribution" with limitation notes.
         */
        Explanation: {
            /** Base Value */
            base_value: number;
            /** Items */
            items: components["schemas"]["ExplanationItem"][];
            /** K */
            k: number;
            /** Method */
            method: string;
            /** Method Version */
            method_version: number;
            /** Other Contribution */
            other_contribution: number;
            /** Score */
            score: number;
        };
        /** ExplanationItem */
        ExplanationItem: {
            /** Contribution */
            contribution: number;
            /** Feature */
            feature: string;
            /** Value */
            value?: number | string | null;
        };
        /**
         * FavoriteBaseline
         * @description Feature 064: the market baseline (flat-bet the favorite) realised for THIS race. Honest
         *     reference line — NOT a profit strategy. All-null when unsettled / no priced horse.
         */
        FavoriteBaseline: {
            /**
             * Dead Heat
             * @default false
             */
            dead_heat: boolean;
            /** Hit */
            hit?: boolean | null;
            /** Horse Number */
            horse_number?: number | null;
            /** Odds */
            odds?: number | null;
            /** Realized Return */
            realized_return?: number | null;
            /** Realized Roi */
            realized_roi?: number | null;
            /**
             * Settled
             * @default false
             */
            settled: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HorseEntry */
        HorseEntry: {
            /** Age */
            age?: number | null;
            /** Entry Status */
            entry_status: string;
            /** Frame */
            frame?: number | null;
            /** Horse Id */
            horse_id: string;
            /** Horse Name */
            horse_name?: string | null;
            /** Horse Number */
            horse_number?: number | null;
            /** Jockey Id */
            jockey_id?: string | null;
            /** Jockey Name */
            jockey_name?: string | null;
            /** Jockey Weight */
            jockey_weight?: number | null;
            /** Odds */
            odds?: number | null;
            /** Popularity */
            popularity?: number | null;
            /** Sex */
            sex?: string | null;
            /** Trainer Id */
            trainer_id?: string | null;
            /** Trainer Name */
            trainer_name?: string | null;
            /** Weight */
            weight?: number | null;
            /** Weight Diff */
            weight_diff?: number | null;
        };
        /** HorseHistoryRow */
        HorseHistoryRow: {
            /** Distance */
            distance?: number | null;
            /** Entry Status */
            entry_status?: string | null;
            /** Finish Order */
            finish_order?: number | null;
            /** Finish Time Sec */
            finish_time_sec?: number | null;
            /** Horse Number */
            horse_number?: number | null;
            /** Last 3F */
            last_3f?: number | null;
            /** Odds */
            odds?: number | null;
            /** Popularity */
            popularity?: number | null;
            /** Race Class */
            race_class?: string | null;
            /** Race Date */
            race_date?: string | null;
            /** Race Id */
            race_id: string;
            /** Race Name */
            race_name?: string | null;
            /** Race Number */
            race_number?: number | null;
            /** Result Status */
            result_status?: string | null;
            /** Track Type */
            track_type?: string | null;
            /** Venue Code */
            venue_code?: string | null;
        };
        /** HorsePrediction */
        HorsePrediction: {
            /** Divergence */
            divergence?: ("market_higher" | "model_higher" | "similar") | null;
            explanation?: components["schemas"]["Explanation"] | null;
            /** Horse Id */
            horse_id: string;
            /** Horse Number */
            horse_number?: number | null;
            /** Market Win Prob */
            market_win_prob?: number | null;
            /** Prior Starts Band */
            prior_starts_band?: ("few" | "some" | "many") | null;
            /** Top2 */
            top2?: number | null;
            /** Top3 */
            top3?: number | null;
            /** Win */
            win?: number | null;
        };
        /** HorseProfile */
        HorseProfile: {
            /** Avg Finish */
            avg_finish?: number | null;
            /** Birth Year */
            birth_year?: number | null;
            /** Dam Name */
            dam_name?: string | null;
            /** Damsire Name */
            damsire_name?: string | null;
            /** Data Source */
            data_source?: string | null;
            /** Horse Id */
            horse_id: string;
            /** Horse Name */
            horse_name?: string | null;
            /** Quinella Rate */
            quinella_rate?: number | null;
            /**
             * Seconds In
             * @default 0
             */
            seconds_in: number;
            /** Sex */
            sex?: string | null;
            /** Show Rate */
            show_rate?: number | null;
            /**
             * Shows In
             * @default 0
             */
            shows_in: number;
            /** Sire Name */
            sire_name?: string | null;
            /**
             * Starts
             * @default 0
             */
            starts: number;
            /** Win Rate */
            win_rate?: number | null;
            /**
             * Wins
             * @default 0
             */
            wins: number;
        };
        /**
         * ImportanceResponse
         * @description Feature 040 US2: split-gain feature importance (display-only, read from metrics_summary).
         *
         *     ``type`` is "gain" — split-gain importance, biased toward high-gain-split features. The front
         *     labels it narrowly ("分割利得(gain)重要度"), not general feature importance.
         */
        ImportanceResponse: {
            /** Model Version */
            model_version: string;
            /**
             * Type
             * @default gain
             */
            type: string;
            /**
             * Values
             * @default []
             */
            values: components["schemas"]["ImportanceValue"][];
        };
        /** ImportanceValue */
        ImportanceValue: {
            /** Feature */
            feature: string;
            /** Gain */
            gain: number;
        };
        /** JobListResponse */
        JobListResponse: {
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["JobRow"][];
        };
        /**
         * JobRow
         * @description One ingestion_jobs row (audit trail; read-only transcription).
         */
        JobRow: {
            /** Completed At */
            completed_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Count */
            error_count?: number | null;
            /** Error Message */
            error_message?: string | null;
            /** Ingestion Job Id */
            ingestion_job_id: string;
            /** Job Type */
            job_type?: string | null;
            /** Processed Rows */
            processed_rows?: number | null;
            /** Retry Count */
            retry_count: number;
            /** Scope */
            scope?: string | null;
            /** Scope Value */
            scope_value?: string | null;
            /** Skipped Rows */
            skipped_rows?: number | null;
            /** Source */
            source?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Status */
            status: string;
            /** Trace Id */
            trace_id?: string | null;
        };
        /** JockeyHistoryRow */
        JockeyHistoryRow: {
            /** Finish Order */
            finish_order?: number | null;
            /** Horse Id */
            horse_id?: string | null;
            /** Horse Name */
            horse_name?: string | null;
            /** Race Date */
            race_date?: string | null;
            /** Race Id */
            race_id: string;
            /** Race Name */
            race_name?: string | null;
            /** Race Number */
            race_number?: number | null;
            /** Result Status */
            result_status?: string | null;
            /** Venue Code */
            venue_code?: string | null;
        };
        /** JockeyProfile */
        JockeyProfile: {
            /** Avg Finish */
            avg_finish?: number | null;
            /** Jockey Id */
            jockey_id: string;
            /** Jockey Name */
            jockey_name?: string | null;
            /**
             * Mounts
             * @default 0
             */
            mounts: number;
            /** Quinella Rate */
            quinella_rate?: number | null;
            /**
             * Seconds In
             * @default 0
             */
            seconds_in: number;
            /** Show Rate */
            show_rate?: number | null;
            /**
             * Shows In
             * @default 0
             */
            shows_in: number;
            /** Win Rate */
            win_rate?: number | null;
            /**
             * Wins
             * @default 0
             */
            wins: number;
        };
        /** JointEntry */
        JointEntry: {
            /** Prob */
            prob: number;
            /** Selection */
            selection: number[];
        };
        /** ModelListResponse */
        ModelListResponse: {
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["ModelVersionRow"][];
        };
        /**
         * ModelVersionRow
         * @description Feature 051: one model_versions row for the admin registry — persisted values ONLY
         *     (metrics_summary transcription, no recomputation = 021 discipline). Missing keys → null
         *     (old models lack train_through — recorded since 050 — and pre-040 runs lack importance).
         */
        ModelVersionRow: {
            /** Adopted */
            adopted?: boolean | null;
            /** Adoption Status */
            adoption_status: string;
            /** Calibration */
            calibration?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Name */
            display_name?: string | null;
            /** Feature Version */
            feature_version?: string | null;
            /** Git Sha */
            git_sha?: string | null;
            /**
             * Has Calibration
             * @default false
             */
            has_calibration: boolean;
            /**
             * Has Importance
             * @default false
             */
            has_importance: boolean;
            /** Label Schema */
            label_schema: string;
            /** Model Family */
            model_family?: string | null;
            /** Model Version */
            model_version: string;
            /** N Model Rows */
            n_model_rows?: number | null;
            /** Objective */
            objective?: string | null;
            /** Purpose */
            purpose?: string | null;
            /** Train Through */
            train_through?: string | null;
            /** Win Auc */
            win_auc?: number | null;
            /** Win Brier */
            win_brier?: number | null;
            /** Win Ece */
            win_ece?: number | null;
            /** Win Log Loss */
            win_log_loss?: number | null;
        };
        /** OddsResponse */
        OddsResponse: {
            /**
             * Estimated
             * @default []
             */
            estimated: components["schemas"]["EstimatedOddsRow"][];
            /** Race Id */
            race_id: string;
            /**
             * Real Exotic
             * @default []
             */
            real_exotic: components["schemas"]["RealExoticOddsRow"][];
            /**
             * Win
             * @default []
             */
            win: components["schemas"]["WinOddsRow"][];
        };
        /** Page[HorseHistoryRow] */
        Page_HorseHistoryRow_: {
            /** Has Next */
            has_next: boolean;
            /** Items */
            items: components["schemas"]["HorseHistoryRow"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** Page[JockeyHistoryRow] */
        Page_JockeyHistoryRow_: {
            /** Has Next */
            has_next: boolean;
            /** Items */
            items: components["schemas"]["JockeyHistoryRow"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** Page[RaceSummary] */
        Page_RaceSummary_: {
            /** Has Next */
            has_next: boolean;
            /** Items */
            items: components["schemas"]["RaceSummary"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** PredictionResponse */
        PredictionResponse: {
            /**
             * Available Models
             * @default []
             */
            available_models: components["schemas"]["AvailableModel"][];
            /** Canonical Consistent */
            canonical_consistent?: boolean | null;
            /**
             * Horses
             * @default []
             */
            horses: components["schemas"]["HorsePrediction"][];
            /** Joint */
            joint?: components["schemas"]["JointEntry"][] | null;
            /** Joint Bet Type */
            joint_bet_type?: string | null;
            /** Joint Logic Version */
            joint_logic_version?: string | null;
            /** Market Prob Source */
            market_prob_source?: "win_odds_vote_share" | null;
            /** Odds As Of */
            odds_as_of?: string | null;
            /** Odds Source */
            odds_source?: ("final" | "prerace") | null;
            /** Race Id */
            race_id: string;
            run?: components["schemas"]["RunAudit"] | null;
        };
        /** RaceDetail */
        RaceDetail: {
            /** Distance */
            distance?: number | null;
            /**
             * Has Results
             * @default false
             */
            has_results: boolean;
            /** Horses */
            horses: components["schemas"]["HorseEntry"][];
            /** Post Time */
            post_time?: string | null;
            /** Race Class */
            race_class?: string | null;
            /** Race Date */
            race_date?: string | null;
            /** Race Id */
            race_id: string;
            /** Race Name */
            race_name?: string | null;
            /** Race Number */
            race_number?: number | null;
            /** Track Type */
            track_type?: string | null;
            /** Venue Code */
            venue_code?: string | null;
        };
        /** RaceSummary */
        RaceSummary: {
            /** Distance */
            distance?: number | null;
            /**
             * Has Results
             * @default false
             */
            has_results: boolean;
            /** Post Time */
            post_time?: string | null;
            /** Race Class */
            race_class?: string | null;
            /** Race Date */
            race_date?: string | null;
            /** Race Id */
            race_id: string;
            /** Race Name */
            race_name?: string | null;
            /** Race Number */
            race_number?: number | null;
            /** Track Type */
            track_type?: string | null;
            /** Venue Code */
            venue_code?: string | null;
        };
        /** RealExoticOddsRow */
        RealExoticOddsRow: {
            /** Bet Type */
            bet_type: string;
            /** Coverage Scope */
            coverage_scope?: string | null;
            /**
             * Is Estimated
             * @default false
             * @constant
             */
            is_estimated: false;
            /** Odds */
            odds?: number | null;
            /**
             * Odds Source
             * @default real
             * @constant
             */
            odds_source: "real";
            /** Selection */
            selection: number[];
            /** Updated At */
            updated_at?: string | null;
        };
        /** RecommendationResponse */
        RecommendationResponse: {
            favorite_baseline?: components["schemas"]["FavoriteBaseline"] | null;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["RecommendationRow"][];
            /** Race Id */
            race_id: string;
            /**
             * Win Policy Status
             * @default no_run
             */
            win_policy_status: string;
        };
        /** RecommendationRow */
        RecommendationRow: {
            /** Bet Type */
            bet_type: string;
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            /**
             * Dead Heat
             * @default false
             */
            dead_heat: boolean;
            /** Double Pseudo */
            double_pseudo: boolean;
            /** Estimated Market Odds Used */
            estimated_market_odds_used?: number | null;
            /** Hit */
            hit?: boolean | null;
            /** Is Estimated Odds */
            is_estimated_odds: boolean;
            /** Logic Version */
            logic_version: string;
            /** Market Odds Used */
            market_odds_used?: number | null;
            /** Prediction Run Id */
            prediction_run_id: string;
            /** Pseudo Odds */
            pseudo_odds?: number | null;
            /** Pseudo Roi */
            pseudo_roi?: number | null;
            /** Realized Return */
            realized_return?: number | null;
            /** Realized Roi */
            realized_roi?: number | null;
            /** Recommendation Id */
            recommendation_id: string;
            /** Selection */
            selection: number[];
            /**
             * Settled
             * @default false
             */
            settled: boolean;
            /** Stake Fraction */
            stake_fraction?: number | null;
        };
        /** RunAudit */
        RunAudit: {
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            /** Logic Version */
            logic_version: string;
            /** Model Version */
            model_version: string;
            /** Prediction Run Id */
            prediction_run_id: string;
        };
        /** SegmentEdgeResponse */
        SegmentEdgeResponse: {
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            /** Date From */
            date_from?: string | null;
            /** Date To */
            date_to?: string | null;
            /**
             * Kind
             * @default segment_edge
             */
            kind: string;
            /** Logic Version */
            logic_version: string;
            /** N Horses */
            n_horses: number;
            /** Note */
            note: string;
            /**
             * Rows
             * @default []
             */
            rows: components["schemas"]["SegmentEdgeRow"][];
        };
        /**
         * SegmentEdgeRow
         * @description One 047 segment row — verbatim from the persisted payload (no derived metrics).
         */
        SegmentEdgeRow: {
            /** Axis */
            axis: string;
            /** Gap */
            gap: number;
            /** Logloss P */
            logloss_p: number;
            /** Logloss Q */
            logloss_q: number;
            /** Mean P */
            mean_p: number;
            /** Mean Q */
            mean_q: number;
            /** N */
            n: number;
            /** Segment */
            segment: string;
            /** Win Rate */
            win_rate: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WinOddsRow */
        WinOddsRow: {
            /** Horse Id */
            horse_id: string;
            /** Horse Number */
            horse_number?: number | null;
            /**
             * Is Estimated
             * @default false
             * @constant
             */
            is_estimated: false;
            /** Odds */
            odds?: number | null;
            /**
             * Odds Source
             * @default real
             * @constant
             */
            odds_source: "real";
            /** Updated At */
            updated_at?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    coverage_api_v1_coverage_get: {
        parameters: {
            query: {
                date_from: string;
                date_to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    segment_edge_api_v1_diagnostics_segment_edge_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegmentEdgeResponse"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_horse_api_v1_horses__horse_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                horse_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HorseProfile"];
                };
            };
            /** @description horse not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_horse_history_api_v1_horses__horse_id__history_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                horse_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_HorseHistoryRow_"];
                };
            };
            /** @description horse not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    jobs_api_v1_jobs_get: {
        parameters: {
            query?: {
                status?: string | null;
                job_type?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_jockey_api_v1_jockeys__jockey_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jockey_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JockeyProfile"];
                };
            };
            /** @description jockey not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_jockey_history_api_v1_jockeys__jockey_id__history_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                jockey_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_JockeyHistoryRow_"];
                };
            };
            /** @description jockey not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    models_api_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelListResponse"];
                };
            };
        };
    };
    calibration_api_v1_models__model_version__calibration_get: {
        parameters: {
            query?: {
                label?: string;
            };
            header?: never;
            path: {
                model_version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    importance_api_v1_models__model_version__importance_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    races_api_v1_races_get: {
        parameters: {
            query?: {
                date?: string | null;
                venue?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RaceSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    race_detail_api_v1_races__race_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                race_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RaceDetail"];
                };
            };
            /** @description race not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description bad race_id */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    odds_api_v1_races__race_id__odds_get: {
        parameters: {
            query?: {
                bet_type?: string | null;
                top?: number;
            };
            header?: never;
            path: {
                race_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OddsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predictions_api_v1_races__race_id__predictions_get: {
        parameters: {
            query?: {
                bet_type?: string | null;
                top?: number;
                model_version?: string | null;
            };
            header?: never;
            path: {
                race_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommendations_api_v1_races__race_id__recommendations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                race_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
